apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/baadist-default: "true"
    io.kompose.service: influxdb
  name: influxdb
spec:
  containers:
  - args:
    - --bolt-path
    - /var/opt/influxdb/influxd.bolt
    - --engine-path
    - /var/opt/influxdb/engine
    - --reporting-disabled
    env:
    - name: DEBUG
      value: "true"
    - name: INFLUX_BUCKET
      value: pm-collection
    - name: INFLUX_ORG
      value: broadband_forum
    - name: INFLUX_PORT
      value: "9999"
    - name: INFLUX_PW
      value: influxdb
    - name: INFLUX_RETENTION
      value: "720"
    - name: INFLUX_ROOT
      value: /var/opt/influxdb
    - name: INFLUX_USER
      value: influxdb
    image: broadbandforum/influxdb:2.0.0-beta.2-3
    name: obbaa-influxdb
    ports:
    - containerPort: 9999
    resources: {}
    volumeMounts:
    - mountPath: /var/opt/influxdb
      name: influxdb-claim0
  restartPolicy: OnFailure
  volumes:
  - name: influxdb-claim0
    persistentVolumeClaim:
      claimName: influxdb-claim0
status: {}
